import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';
import Month from '../components/Month';
import cal2022Data from '../public/cal2022.json';

export default function Home() {
  const q1 = ['jan', 'feb', 'mar'];
  const q2 = ['apr', 'may', 'jun'];

  const q3 = ['jul', 'aug', 'sep'];

  const q4 = ['oct', 'nov', 'dec'];
  const quarters = [q1, q2, q3, q4];

  const jan = cal2022Data['jan'];
  const feb = cal2022Data['feb'];
  const mar = cal2022Data['mar'];
  const apr = cal2022Data['apr'];
  const may = cal2022Data['may'];
  const jun = cal2022Data['jun'];
  const jul = cal2022Data['jul'];
  const aug = cal2022Data['aug'];
  const sep = cal2022Data['sep'];
  const oct = cal2022Data['oct'];
  const nov = cal2022Data['nov'];
  const dec = cal2022Data['dec'];

  const monthNames = [
    'JAN',
    'FEB',
    'MAR',
    'APR',
    'MAY',
    'JUN',
    'JUL',
    'AUG',
    'SEP',
    'OCT',
    'NOV',
    'DEC',
  ];

  return (
    <Page>
      <StyledContainer className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {quarters.map((q) => {
          return (
            <Qourter>
              {q.map((monthName) => (
                <Month
                  monthName={monthName}
                  monthData={cal2022Data[monthName]}
                />
              ))}
            </Qourter>
          );
        })}
      </StyledContainer>
    </Page>
  );
}

const Qourter = styled.div`
  display: grid;
  /* gap: 1rem; */
  padding: 3rem 0;
  border-bottom: 0.2px solid rgba(0, 0, 0, 0.1);
  &:last-child {
    border-bottom: none;
  }
`;

const StyledContainer = styled.div`
  outline: 2px solid lightgray;
  padding: 3rem;
  /* background-color:  lightgray ; */
  display: grid;
  /* gap: 2rem; */
`;

const Page = styled.div`
  padding: 2rem 0;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
